server:
  port: ${SERVER_PORT:8080}
  error:
    include-stacktrace: never

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mamb_hotel_db}
    username: ${SPRING_DATASOURCE_USERNAME:mamb_user}
    password: ${SPRING_DATASOURCE_PASSWORD:mamb_pass}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: true

  flyway:
    enabled: true

logging:
  level:
    org.hibernate.SQL: debug